version: 2.1
orbs:
  annotate: nr-futurehack/annotate@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
    command-tests:
      docker:
        - image: cimg/base:current
      steps:
        - checkout
        - annotate/debug
        - annotate/step
        - annotate/send
        - annotate/dashbaord
workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: nr-futurehack/annotate
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
